Drive-Mapping:
  - P: "C:/Users/GergelyToth2/OneDrive - EPAM/Projects/Bayer"
  - R: "C:/Users/GergelyToth2/source/repos"
  - W: "C:/Users/GergelyToth2/OneDrive - EPAM/Projects/Bayer/bayer-int/wba-azure-automation-poc"
  - T: "D:/OneDrive - Personal/Source"
  - V: "D:/OneDrive - Personal/Source/Gwergilius/Fallout Terminal Hacker.Android"
