# Log retention configuration (in days)
# Older log entries will be removed on startup
Log-Retention-Days: 30

Drive-Mapping:
  - P: "C:/Users/ATFZZ/OneDrive - EPAM/Projects/Bayer"
  - W: "C:/Users/ATFZZ/OneDrive - EPAM/Projects/Bayer/bayer-int/wba-azure-automation-poc"
